version: "3.8"
services:
  web:
    container_name: web
    restart: always
    build: .
    ports:
        - "3001:3001"
    volumes:
        - .:/usr/src/app

  db:
      image: postgres
      ports:
        - "5432:5432"
      restart: always
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}